### ISSUE TITLE
アクセス制限

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#1240]
https://baserproject.github.io/5/ucmitz/specification/baser-core/common/permission.html

**Comment by seto1** [comment]
ブランチ: [dev-permission](https://github.com/baserproject/ucmitz/tree/dev-permission)

<img width="919" alt="スクリーンショット 2022-10-15 18 53 39" src="https://user-images.githubusercontent.com/30764014/195981479-16ff9fdf-c056-4315-b11e-5ad4a82602f3.png">

- TODO
	- セレクトボックスで選択したらURLに補完で入力する
	    - UI検討 
	- 依存先の表示・設定
	- グループ作成時のデフォルト値の適用
	- アクセス制限
		- BcAdminAppController::beforeFilter
		- BcApiController::initialize ?
	- クエリパラメータを無視しているか確認
	- 設定ファイルが存在しない場合の動的生成
		- プラグインインストール時に候補URLをリストアップ
		- もしくは、アクセス制限画面にアクセスしたタイミングで全機能チェック&キャッシュ
- メモ
	- パラメータのチェックは各アクションで行う

**Comment by ryuring** [comment]
@seto1 瀬戸くんの案を受けた上で、さらに僕の案を入れておきます。

- /admin/plugin-name/* ができるUIとする
- 基本的には、プラグインも設定ファイルを記載前提とする
- プラグインのインストール時に設定ファイルを元にビルド（レコード生成）を行う
- プラグインのインストール時、プラグインの設定ファイルがない場合は、/admin/plugin-name/* を追加する
- ユーザーグループごとにアクセス制限設定の再ビルド機能を持つ
- 管理画面に依存するAPIは、別途、設定ファイルでハードコーディングしレコードでは持たせない

おそらく、基本的には、アプリケーション側が提供する初期設定（初期ビルド）で運用する事が多く、カスタマイズにおける微調整にて微調整がしやすいUIがあればよいかなと考えています。

なお、API側については、基本全てアクセス不可を前提として初期ビルドする。
もしくは、API全体の有効、無効設定をもたせて、デフォルトオフにしておく。


もしくは、APIの利用について

**Comment by ryuring** [comment]
@seto1 こちらにまとめておきました。
https://baserproject.github.io/5/ucmitz/specification/baser-core/common/permission.html

UIについては、権限設定パターンA＋自由入力欄があればよいかなと考えています。

**Comment by ryuring** [comment]
@seto1 UIも含めて設計書にまとめました。
https://baserproject.github.io/5/ucmitz/specification/baser-core/common/permission.html

また、ブランチも切って本家に push してます。
ぼちぼち開発進めますね。
https://github.com/baserproject/ucmitz/tree/dev-%231240
