### ISSUE TITLE
BcRedirectSubSiteFilter::process のユニットテスト実装

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#1313]
ヘッダーコメントに仕様を書いたので参考にする

**Comment by HungDV2022** [comment]
@ryuring すみません、実装方法を教えていただけませんか

**Comment by ryuring** [comment]
@HungDV2022 実行については、plugins/baser-core/tests/TestCase/Middleware/BcRequestFilterMiddlewareTest.php を参考にしてください。

Site データのフィクスチャが必要です。
例えば、次にサイトを準備します。
- メインサイト：idが1のサイト
- サブサイト：main_site_id が 1 で、device が smartphoneのサイト

そして、ユーザーエージェントを smartphone の状態で、アクセスし、サブサイトのURLにリダイレクトすれば OKです。

「smartphoneの状態」は、BcAgent::isMatchDecisionKey() と plugins/baser-core/config/setting.php の 364行目を参考にして作ってください。
