### ISSUE TITLE
イベントを洗い出してドキュメントにまとめる

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#1341]
[イベント一覧](https://docs.google.com/spreadsheets/d/1YT5PuZQdDNU0wrZdqYbh74KuLSw1SIt4_EKwPWOfDKA/edit#gid=1008573296) にイベントを洗い出してまとめる。

1. // EVENT でフォルダ内検索を実施
2. レイヤー名を記入（Controller / Model / View / Helper）
3. クラス名を記入（プレフィックスがある場合はプレフィックスを先頭につける 例：Admin/UsersController）
4. イベント名を記入（// EVENT に続くテキスト 例：Users.searchIndex）
5. 引数を記入（キーと変数名、引数が多い場合はスプレッドシートの列を増やす）

**Comment by ryuring** [comment]
@hiraokakoichi ユニットテストの指示出しが間に合わなくなってきたのでこちらをお願いしたいです。

すでに記載にしているものについても、イベント名が上記のルールに則っていないので見直しをお願いします。

**Comment by hiraokakoichi** [comment]
@ryuring 
もっと適切な並び順があるかもしれませんが、「// EVENT」の文字列検索でヒットするイベントの洗い出しは完了しました！

**Comment by ryuring** [comment]
@hiraokakoichi 平岡さん、ありがとうございました！
並び順はこちらで整理しました。
クローズしますね。
