### ISSUE TITLE
PasswordRequestsService::update のユニットテスト実装

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#1351]
コメントヘッダーの仕様を確認する

**Comment by zebeel** [comment]
@ryuring 
ユーザーが存在しない場合は以下のエラーが発生しました。
> TypeError: BaserCore\Service\PasswordRequestsService::update(): Return value must be of type ?Cake\Datasource\EntityInterface, bool returned

ユーザーが存在する場合は以下のエラーが発生しました。

> Cake\Core\Exception\CakeException: Could not send email: Since fakerphp/faker 1.14: Accessing property "text" is deprecated, use "text()" instead.

**Comment by ryuring** [comment]
こちらメール送信のテストができるように戻り値を変更しました。
