### ISSUE TITLE
BlogPostsController::initialize のユニットテスト実装

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#1487]
メソッドのコメントヘッダーを確認する

**Comment by HungDV2022** [comment]
@ryuring 
BlogPostsControllerはすでにテストを実装したみたいです。
確認お願いします。
https://github.com/baserproject/ucmitz/issues/1414

**Comment by ryuring** [comment]
@HungDV2022 ありがとうございます。クローズします。
