### ISSUE TITLE
BlogPostsService::allowPublish のユニットテスト実装

### ISSUE THREAD

**Issue by HungDV2022** [baserproject/ucmitz#1601]

**Comment by HungDV2022** [comment]
<img width="590" alt="スクリーンショット 2022-12-21 8 21 43" src="https://user-images.githubusercontent.com/110375578/208798220-abe63563-44e8-4a94-b41e-3ab489dc6ff6.png">
@ryuring `ラッパーメソッドのためテスト不要`を書いてありますからこちらのイシューは対応不要でしょうか。

**Comment by ryuring** [comment]
@HungDV2022 そうですね。失礼しました。対応不要です。
