### ISSUE TITLE
ウィジェットエリア管理	API	リストデータ取得 を実装

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#1619]
[ウィジェットエリア設計書](https://baserproject.github.io/5/ucmitz/specification/bc-widget-area/widget_areas/index) を参照する

**Comment by HungDV2022** [comment]
@ryuring 
https://github.com/baserproject/ucmitz/issues/1617
こちらイシューと重複しているようです。
確認お願いします。

**Comment by ryuring** [comment]
@HungDV2022 こちらは重複ではないです。設計書側の漏れですね。
WidgetAreasService に getList() を実装し、WidgetAreasController に、list() を実装してください。

find('list') を使います。
