### ISSUE TITLE
short_open_tag （<?  ?>）を使わない

### ISSUE THREAD

**Issue by cu-morishita** [baserproject/ucmitz#180]
ucmitzでshort_open_tagが使用されているのですが、
MAMPやXAMPP等の実装系環境ではまだ初期値が無効のものが多いそうです。

https://helog.jp/php/short_open_tag/

システム要件にも必須として追記が必要となってくるのではないかと思うのですが、いかがでしょうか？
現状、short_open_tagが有効となっていない環境ではログイン画面に入った時点で「Class 'BcUtil' not found」エラーが発生し、ログイン画面を参照できない状況です。
（BcUtilをuseする箇所がshort_open_tagで記載されており、PHPタグとして認識されないため）
![スクリーンショット 2021-07-13 16 33 13](https://user-images.githubusercontent.com/60252780/125410839-43927b80-e3f8-11eb-82f8-2161b527bcd2.png)

@ryuring @humuhimi

**Comment by gondoh** [comment]
@cu-morishita 
今後の流れとしては <?= は残るけど <? は消えるかもって感じみたいっすね。
https://qiita.com/rana_kualu/items/180aff848169e1733631

<?= はいいとしても <? はなしのほうがいいかもしれません。

**Comment by ryuring** [comment]
@cu-morishita あ、そうですね、<?= は、イキで、<? はミスです。ガンガンなおしてもらえると！

**Comment by humuhimi** [comment]
反映完了したので、閉じますっ
