### ISSUE TITLE
WebAPI 一覧でステータスをチェックする

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#1866]
@HungDV2022 次のルールでステータスチェックを行い、 [WebAPI一覧](https://docs.google.com/spreadsheets/d/1YT5PuZQdDNU0wrZdqYbh74KuLSw1SIt4_EKwPWOfDKA/edit#gid=1129992221)
 の「ステータス欄」にて、終わったところに●を付けてください。

- 入力エラー
  - PersistenceFailedException → 400
    - `__d('baser', '入力エラーです。内容を修正してください。')`
- データが見つからない
  - RecordNotFoundException → 404
    - `__d('baser', 'データが見つかりません。')`
- それ以外
  - Throwable → 500
    - `__d('baser', 'データベース処理中にエラーが発生しました。) . $e->getMessage()`

なお、API のコントローラーで、`BcException` を利用しているところは、全て `Throwable` に変更してください。

テストにも影響があると思いますので、テストも調整してください。

**Comment by ryuring** [comment]
@HungDV2022 これ完了ですよね？そうでしたらクローズしておいてください。

**Comment by HungDV2022** [comment]
対応完了したのでクローズします。

**Comment by ryuring** [comment]
@HungDV2022 ありがとうございました！
