### ISSUE TITLE
fix #1708 管理側「最近の動き」が0件のとき一覧画面の表示が崩れている動作を修正

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#1869]
このチケットは、baserCMS５のフォークが作成された、baserCMSバージョン4.4.7以降に作成されたコミットを baserCMS５に移行するためのチケットです。
移行が必要かどうか判断し必要な場合は、ucmitz レポジトリに、移行版のプルリクエストを作成してください。そうでない場合はクローズしてください。
移行元のコミットはこちらです。
https://github.com/baserproject/basercms/commit/ff4a51cb78c009ff1a8f014712f59b0f27cfca43

**Comment by fuchigam1** [comment]
対応不要であることを確認済み。クローズ！
