### ISSUE TITLE
In ProgressのIssueが既に完了しているか確認する

### ISSUE THREAD

**Issue by HungDV2022** [baserproject/ucmitz#1871]
ucmitz3-API & UnitTest の In Progress ステータスの Issue について、自分以外のものが既に完了してるかどうか確認をお願いします。

**Comment by HungDV2022** [comment]
@ryuring 
既に対応したイシューをクローズしました。
のろるタスクは対応中と未対応です。
確認お願いします。

**Comment by ryuring** [comment]
@HungDV2022 確認ありがとうございます。下記３つについてフンさんの方で対応をお願いします。
https://github.com/baserproject/ucmitz/issues/1735
https://github.com/baserproject/ucmitz/issues/1737
https://github.com/baserproject/ucmitz/issues/1409
