### ISSUE TITLE
インストール時にテーブルカラムのプレフィックスを求められるが生成された際にプレフィックスがつかない

### ISSUE THREAD

**Issue by t-uchiba** [baserproject/ucmitz#1905]
php8.1
mysql5.7.40

<img width="724" alt="スクリーンショット 2023-03-03 15 13 14" src="https://user-images.githubusercontent.com/37653901/222645809-fb36756b-ebad-4018-beb0-0dbeed5750f8.png">
<img width="1141" alt="スクリーンショット 2023-03-03 15 14 08" src="https://user-images.githubusercontent.com/37653901/222645831-5bffb69f-8eb7-495a-98fc-23a77c6448e8.png">

**Comment by ryuring** [comment]
@t-uchiba ありがとうございます。こちらまだ未対応なんです。こちらの Issue でちょうど昨日から進めているところでした。
https://github.com/orgs/baserproject/projects/7?pane=issue&itemId=21487601

Cakeがデフォルト未対応になってるので少し苦戦してます。
