### ISSUE TITLE
REST API のURL記入

### ISSUE THREAD

**Issue by HungDV2022** [baserproject/ucmitz#2057]
[API一覧](https://docs.google.com/spreadsheets/d/1YT5PuZQdDNU0wrZdqYbh74KuLSw1SIt4_EKwPWOfDKA/edit#gid=1129992221) の次のメソッドについて、REST API 用の メソッドとURLを記入する

- index: [GET] /baser/api/{plugin-name}/{controller_name}/action_name.json
- view: [GET] /baser/api/{plugin-name}/{controller_name}/action_name/1.json
- add: [POST] /baser/api/{plugin-name}/{controller_name}/action_name.json
- edit: [PATCH] /baser/api/{plugin-name}/{controller_name}/action_name/1.json
- delete: [DELETE] /baser/api/{plugin-name}/{controller_name}/action_name/1.json

例）
|  メソッド  |  REST API URL  |
| ---- | ---- |
|  GET  |  /baser/api/content_folders/1.json  |

**Comment by ryuring** [comment]
@nghiem-mb こちら急いでいたのでこちらで実施しました。クローズします。
