### ISSUE TITLE
テーマプラグインのレイアウトテンプレートが設定できない

### ISSUE THREAD

**Issue by t-uchiba** [baserproject/ucmitz#2062]
発生バージョン：ucmitz3.0.26
セグメント：管理画面
ページ：固定ページ編集

・独自テーマプラグイン作成
・レイアウトテンプレート（ex. top.php）を作成してもレイアウト設定欄に表示されない

**Comment by ryuring** [comment]
@t-uchiba こちらのコミットでなおっているか確認お願いします。
https://github.com/baserproject/ucmitz/commit/2100216ea5de5f9817529813448caf8f662a2892

**Comment by ryuring** [comment]
なおってるとの事でクローズ
