### ISSUE TITLE
管理画面 ブログの記事一覧を表示した際にjsonへのアクセスに失敗する

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#2065]
http://localhost:8081/_baser/ucmitz/baser/api/baser-core/utilities/save_search_opened/AdminBcBlogBlogPostsIndex1.json

<img width="1362" alt="スクリーンショット 2023-03-14 18 05 50" src="https://user-images.githubusercontent.com/30764014/224950774-77a82a83-e84e-4b3a-b712-d4433f1a29dd.png">

**Comment by ryuring** [comment]
こちら解消しているのでクローズします。
