### ISSUE TITLE
アップローダでファイルをアップロードすると、処理が完了せずローディング表示のままとなる

### ISSUE THREAD

**Issue by fuchigam1** [baserproject/ucmitz#2113]
## 再現手順

- プラグイン アップローダを有効化する
- ファイル一覧画面から、画像ファイルを選んでアップロードする
    - → ローディング表示のままとなる
- ※画面をリロードすると、アップロード時に選択したファイル自体は上がっている

![sc_uploader_files_index](https://user-images.githubusercontent.com/1115768/226087949-ebfdbf89-fce5-44c0-bdb1-bad4605a40dd.png)

**Comment by ryuring** [comment]
こちらのコミットで解消
https://github.com/baserproject/ucmitz/commit/2c0dc5deb0e41e908031e4128957154a71c96181
