### ISSUE TITLE
アップローダでファイルを削除すると、処理が完了せずローディング表示のままとなり、「処理に失敗しました」表示がなされる

### ISSUE THREAD

**Issue by fuchigam1** [baserproject/ucmitz#2114]
### 手順
- ファイル一覧画面から、画像ファイルを選んで削除を指定する
    - → ローディング表示のままとなる
    - → 「処理に失敗しました」と表示される
- 画面をリロードすると、削除指定したファイルは削除されている。ファイル実体も削除されている
![sc_uploader_files_index_delete](https://user-images.githubusercontent.com/1115768/226088153-84128862-a7cd-43ad-b875-418551282e98.png)

**Comment by ryuring** [comment]
こちらのコミットで解消
https://github.com/baserproject/ucmitz/commit/2c0dc5deb0e41e908031e4128957154a71c96181
