### ISSUE TITLE
[ブログ]ブログ記事詳細画面でカテゴリ新規追加できない

### ISSUE THREAD

**Issue by kaburk** [baserproject/ucmitz#2226]
カテゴリ追加API関連の問題と思われます。

<img width="547" alt="スクリーンショット 2023-04-04 16 24 26" src="https://user-images.githubusercontent.com/310333/229719063-08d7bbaa-c7ea-4822-897a-9202874253e2.png">
<img width="563" alt="スクリーンショット 2023-04-04 16 24 31" src="https://user-images.githubusercontent.com/310333/229719084-4d75d107-c778-4313-8e3b-a14faacc098b.png">
<img width="1678" alt="スクリーンショット 2023-04-04 16 24 48" src="https://user-images.githubusercontent.com/310333/229719094-8e66f1b6-2592-4018-9f2b-3c4bcc213068.png">

**Comment by ryuring** [comment]
コミットが特定できませんが、どこかのタイミングでなおしていますのでクローズしますね。
システム管理者、サイト運営者で確認しました。
