### ISSUE TITLE
[Web API] 固定ページ（一覧&詳細）の取得で非認証ユーザーにも草稿が返却される

### ISSUE THREAD

**Issue by YusukeHirao** [baserproject/ucmitz#2284]
Ref: https://baserproject.github.io/5/web_api/baser_api/baser-core/pages/index

`GET /baser/api/baser-core/pages.json`

のみで、レスポンスボディの草稿（`draft`）に内容が含まれる。

nullもしくは、draftフィールドを含めないべき。

**Comment by ryuring** [comment]
こちらのコミットで対応しましたのでクローズします。
https://github.com/baserproject/ucmitz/commit/eca9141d7ba2944721b50dc7415ea5cdb297e5e1
