### ISSUE TITLE
admin管理画面でログインしてる場合spa版管理画面でのjwt認証がうまく行かない問題

### ISSUE THREAD

**Issue by humuhimi** [baserproject/ucmitz#339]
admin管理画面でログインしてる場合session認証が先に入ってくるためApi/UsersController-refresh_token()内のjwt認証がうまくいかない。
どちらも同時にできるように変更必

**Comment by ryuring** [comment]
@humuhimi こちらで改善できていると思います。
https://github.com/baserproject/ucmitz/commit/8283e1e409487120d571e861fdfc6c96cc0fee98

問題なければクローズお願いします。

**Comment by humuhimi** [comment]
@ryuring ありがとうございます!
