### ISSUE TITLE
デバッグモードの切り替えについて検討

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#376]
## やりたいこと

.env.example の `DEBUG` を `false` にしつつローカルやgithubでテストが実行される時だけデバッグモードを有効にしたい

## 理由

- デバッグモードのままサイト公開されるリスクを減らすためデバッグモードはデフォルト無効にしたい
- デバッグモードが無効だとテストが失敗する

**Comment by seto1** [comment]
このあたり

https://github.com/baserproject/ucmitz/blob/dev/config/.env.example#L17
https://github.com/baserproject/ucmitz/blob/dev/config/app_local.example.php#L18

https://docs.github.com/ja/actions/learn-github-actions/environment-variables
> GitHubはそれぞれのGitHub Actionsワークフローの実行に対してデフォルトの環境変数を設定します。 ワークフローファイル中でカスタムの環境変数を設定することもできます。

https://github.com/baserproject/ucmitz/blob/dev/.github/workflows/test.yml

**Comment by seto1** [comment]
テスト用の.envを読み込む処理を作成したがエラー多数
https://github.com/seto1/ucmitz/commit/ac82ede1a033d94b7c0eb2f841bdffcb1ce626bc
関係なさそうなエラーも含まれてそうなのでいったん保留
https://github.com/seto1/ucmitz/runs/7086827108

**Comment by ryuring** [comment]
@seto1 単純にデフォルト false にして、 PHPUnit実行の時は強制的に `Configure::write('debug', true)` で書き換える、じゃダメそう？？

**Comment by seto1** [comment]
@ryuring テスト時用の環境変数を設定できると便利かなと思い、この実装を試していました。
特に自分の場合、開発環境のURLが `http://ucmitz.localhost:8081/` なので、テスト時だけURLを `https://localhost` と判定してくれるとassertの部分で大分ありがたいです。

**Comment by ryuring** [comment]
@seto1 ちと検討します。

**Comment by ryuring** [comment]
こちら、デフォルト off にして、テストの時に、bin/cake setup test を実行することで、debug が true になるようにしています。
GitHubActionsの際には、上記コマンドを実行する仕様としました。
問題あれば、reopen してください。
