### ISSUE TITLE
Helperがあまりにも多すぎるので分離した方がいいのでは問題

### ISSUE THREAD

**Issue by humuhimi** [baserproject/ucmitz#433]
@ryuring 
BcAdmin~Helperなど管理画面用のヘルパーだったり、できるだけ用途に応じてフォルダを分けた方がファイル探しやすい気がするのですがどうでしょうか?

**Comment by ryuring** [comment]
@humuhimi Admin系のヘルパを設計する際、分割を検討したんですが、Cakeの仕様として、Helperフォルダ直下のファイルしか読み出せないという問題があり分割はあきらめたという経緯があります。
というわけで、並べ替えやすい命名規則にすることにしました。

**Comment by humuhimi** [comment]
@ryuring 
承知しました！　また、月曜日お聞かせ願います！
