### ISSUE TITLE
CreatePagesマイグレーションの実行に失敗する

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#447]
>  == 20220117081801 CreatePages: migrating
> PDOException: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'pages' already exists in /var/www/html/_baser/ucmitz/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:192

pagesテーブルを2回作成しようとして失敗している

https://github.com/baserproject/ucmitz/blob/dev/plugins/baser-core/config/Migrations/20210316065511_Initial.php#L40
https://github.com/baserproject/ucmitz/blob/dev/plugins/baser-core/config/Migrations/20220117081801_CreatePages.php#L17

**Comment by humuhimi** [comment]
マージされてるので、closeしますね！
ありがとうございました
