### ISSUE TITLE
BcBaserHelper::css と BcBaserHelper::jsについての仕様検討

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#557]
js
https://github.com/baserproject/ucmitz/blob/dev/plugins/baser-core/src/View/Helper/BcBaserHelper.php#L195
> public function js($url, $inline = true, $options = [])

css
https://github.com/baserproject/ucmitz/blob/dev/plugins/baser-core/src/View/Helper/BcBaserHelper.php#L1522
> public function css($path, $options = [])

- jsは$inline引数が存在するがcssには存在しない
- ~~css関数呼び出し時、4系の際はヘッダーに追加されたがucmitzだとinline出力がデフォルト~~
    - 4系もinlineがデフォルト

**Comment by seto1** [comment]
仕様の共通化と互換性について

**Comment by ryuring** [comment]
js の引数は、$url, $options = [] の２つにして、inline = false をデフォにする

**Comment by seto1** [comment]
@ryuring 対応を進めているうちにひとつ問題を見つけました。

レイアウトファイルでBcBaserHelper->scriptsが呼び出された後に、inlineがfalseでjs・css関数を呼び出した場合は何も出力されないということです。

仕様としては当然で、この仕様を知っている人にとっては問題ないですが、人にとってはけっこうハマリポイントだと思います。

ドキュメントに記載でカバーするというのも考えられますが、デフォルトはinline trueの方が親切な気がしてきました。
その場合はinlineをfalseにするケースが増えるので、第2引数でinlineを指定できたほうが便利です。

**Comment by ryuring** [comment]
> レイアウトファイルでBcBaserHelper->scriptsが呼び出された後に、inlineがfalseでjs・css関数を呼び出した場合は何も出力されないということです。

確かにそうですね。

やっぱり、inline true が親切かな。第2引数で指定できるように統一しましょうか。 @seto1
