### ISSUE TITLE
【ログイン】クッキー保存機能

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#56]
下記の理由により廃止検討
- FB/TWが現在同様の機能を提供していない
- モダンブラウザで標準実装されている

**Comment by humuhimi** [comment]
・ログイン状態のチェックボックスにチェックが入った状態でログインした場合ログイン状態をクッキーに保存する。
・管理画面にアクセスする際にクッキーをチェック→ログイン情報あれば、その情報で認証を行う→成功時にアクセスURLに移動
