### ISSUE TITLE
【アクセス制限管理】ポップアップウインドウ調整

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#572]
メソッド（GET / POST）がUIとしてわかりにくいので検討する
※ 権藤さん相談

**Comment by ryuring** [comment]
@gondoh こちらの件ですが、次のリストに変更してもいいですか？

- 全て
- 表示のみ
- 表示と編集

**Comment by gondoh** [comment]
@ryuring 　いいと思います！
