### ISSUE TITLE
【ログイン】nameでログインできるようにする

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#58]
表示はEメールでなくアカウント名で統一し、Eメールでも、nameでログインできるようにする。
Eメールも nameもユニークとなるようにバリデーションを設定する。

**Comment by humuhimi** [comment]
アカウント名でログインできるか確認

**Comment by humuhimi** [comment]
@ryuring 
なんどもすみません。
こちらのイシューってEメールとアカウント名両方でログインできることを指してるんですよね？
再度確認まで！

**Comment by ryuring** [comment]
> こちらのイシューってEメールとアカウント名両方でログインできることを指してるんですよね？

そういうことです！
