### ISSUE TITLE
BcPageHelperのリンク用の関数について検討

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#586]
## 対象

- getNextLink
- nextLink
- getPrevLink
- prevLink

## 例

```
/**
 * ページカテゴリ間の次の記事へのリンクを出力する
 */
public function nextLink($title = '', $options = [])
{
	echo $this->getNextLink($title, $options);
}
```

## 疑問点

- 「固定ページ」ではなく「記事」という表記
- ページカテゴリが何を指すのか分かりづらい
- BcPageHelper内の関数なのに、取得対象が固定ページだけでなくコンテンツすべて

**Comment by ryuring** [comment]
なるほど、過去の経緯の問題ですね

昔はページカテゴリベースの固定ページだったのが、コンテンツ管理に移行になった事に起因しています。

BcPageHelperにあるより、BcContentsHelperにあるべきですね。

メソッド説明としては

```
フォルダ内の次のコンテンツへのリンクを出力する
```
というのが正しい表現だと思います。

**Comment by ryuring** [comment]
実装を BcContentsHelper に移行して、@deprecated にした上で、後方互換を考慮する感じでしょうか。
