### ISSUE TITLE
【パスワード再登録】validation errorが1項目に2つ以上発生した際、アイコンがずれる

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#59]
validation errorが1項目に2つ以上発生した際、アイコンがずれる

**Comment by humuhimi** [comment]
@ryuring 
こちらのアイコンがずれるについてですが、この箇所(ユーザー情報編集)であってますか？
![image](https://user-images.githubusercontent.com/35215680/114344243-0d8ff200-9b92-11eb-9a0d-8aeb7c95ec5c.png)

**Comment by ryuring** [comment]
@humuhimi ログイン画面から「パスワードを忘れた場合はこちら」をクリックした画面です。こちらも調整必要そうですね。

**Comment by humuhimi** [comment]
エラーが一つの場合
![image](https://user-images.githubusercontent.com/35215680/115336005-e60fd980-a1d0-11eb-9e15-cde81567c605.png)
エラーが複数の場合
![image](https://user-images.githubusercontent.com/35215680/115336052-0049b780-a1d1-11eb-88f0-224e56b8ba0e.png)
