### ISSUE TITLE
固定ページ プレビュー時にエラーになる

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#601]
```
Cake\Utility\Inflector::camelize(): Argument #1 ($string) must be of type string, null given, called in /var/www/html/_baser/ucmitz/plugins/baser-core/src/Controller/Admin/PreviewController.php on line 64
```

**Comment by seto1** [comment]
- PagesDisplayService の「Page」という表記を「Pages」に変更する

- サブドメインで動作させるためにはContentsServiceのencodeParsedUrlの以下の行の削除が必要

```
array_splice($directory, 1, 0, [$parsedUrl['subDomain']]);
```

ただ、そもそもサブドメイン対応のために追加されたコードのようなので影響の確認は必要

https://github.com/baserproject/ucmitz/commit/d7cd3f897cc0323be5eebf7c6b499bd7b95e2853#diff-ee5ab29280473adf7996588958e0f303406a22b9473b307482f7828f1bd026d6R1244

- 非公開中の固定ページの確認ができない

**Comment by ryuring** [comment]
@seto1 こちら仕様見直してリファクタリングしました。
https://baserproject.github.io/5/ucmitz/specification/baser-core/common/preview

クローズします。
