### ISSUE TITLE
固定ページ 編集画面でゴミ箱ボタンを押すとエラー

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#609]
> Expression `Contents.id` is missing operator (IS, IS NOT) with `null` value.

編集画面ではなく、コンテンツ管理のツリー上から「ゴミ箱に入れる」ボタンを押した場合は正常に動作する

**Comment by seto1** [comment]
## 原因

- cake4系になってリクエストデータの形式が、コンテンツタイプごとに異なるようになった
	- cake2では `$this->request->data['Content']['id']` でコンテンツIDがとれた
	- cake4だと `$this->request->getData('Contents.id')` だったり `$this->request->getData('ContentFolders.content.id')` だったりする
- ContentsController->deleteにコンテンツタイプごとに条件分岐が記載されているが、固定ページの記載がないことが原因
	- https://github.com/baserproject/ucmitz/blob/dev/plugins/baser-core/src/Controller/Admin/ContentsController.php#L343

## 対応案

- コンテンツIDをURLに持たせる
	- 現状: baser/admin/baser-core/contents/delete
	- 変更後: baser/admin/baser-core/contents/delete/1
- 各コンテンツのコントローラーからビューにコンテンツIDを渡すようにする
- これで条件分岐が不要になりシンプルになる
- コミット: https://github.com/seto1/ucmitz/commit/9b6bdb5f1a4be00ce60cff040a4b4cfe7b9bf31e
	- 要テスト調整

## 検討

- コンテンツ削除のURLを変更してもいいか
- 削除時のイベントのテストが正常に動作していない状態なので仕様検討が必要
	- https://github.com/baserproject/ucmitz/blob/dev/plugins/baser-core/tests/TestCase/Controller/Admin/ContentsControllerTest.php#L416
		- beforeDeleteで削除対象を指定しているがコントローラーに渡されていない状態
		- afterDeleteの処理が実装途中
	- beforeDeleteとafterDeleteでデータに干渉できるようにするかどうか
		- baser4では処理なし
			- https://github.com/baserproject/basercms/blob/dev-4/lib/Baser/Controller/ContentsController.php#L457

## メモ

- entryEventToMock 内で発生したエラーはcatchしないとユニットテストが失敗にならなく、また以降の処理も実行されない
    - 例: 以下の箇所でコンテンツの取得に失敗してエラーになっているがエラーメッセージが表示されなく、` $contentsController->delete` 以降のテストも実行されない状態
        - https://github.com/baserproject/ucmitz/blob/dev/plugins/baser-core/tests/TestCase/Controller/Admin/ContentsControllerTest.php#L427

**Comment by ryuring** [comment]
こちら、削除処理がごちゃごちゃしてたのでリファクタリングしてなおしました。 @seto1
