### ISSUE TITLE
管理画面にログインした状態でucmitzの環境を再構築し、再度管理画面にアクセスするとエラーになる

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#612]
```
2022-06-08 16:20:15 error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "sites" in /var/www/html/_baser/ucmitz/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php on line 509
Stack Trace:
- /var/www/html/_baser/ucmitz/vendor/cakephp/cakephp/src/ORM/Table.php:1541
- /var/www/html/_baser/ucmitz/plugins/baser-core/src/Service/SitesService.php:73
- /var/www/html/_baser/ucmitz/plugins/baser-core/src/Service/AppService.php:63
- /var/www/html/_baser/ucmitz/plugins/baser-core/src/Service/AppService.php:44
- /var/www/html/_baser/ucmitz/plugins/baser-core/src/Controller/AppController.php:152
- /var/www/html/_baser/ucmitz/plugins/baser-core/src/Controller/BcAppController.php:167
- /var/www/html/_baser/ucmitz/plugins/baser-core/src/Controller/Admin/BcAdminAppController.php:276
```

以下の流れで存在しないサイト情報を取得しようとしてエラーになっている

```
AppService->getViewVarsForAll
AppService->getCurrentSite
SitesService->get
```

git cloneからやり直して環境を新しくしたはずなのに、 ログイン状態を維持しているのが問題かも

cookieの`PHPSESSID`を削除するとアクセスできるようになる

**Comment by seto1** [comment]
セッションファイルの保存先が個別でないことが原因
https://github.com/baserproject/ucmitz/blob/dev/config/app.php#L400
https://book.cakephp.org/4/ja/development/sessions.html#id3

baser4のようにtmp配下に保存するようにすると解決

> php - php.ini ファイルの標準セッティングに従ってセッションを保存します。
> cake - セッションをファイルとして app/tmp/sessions に保存します。ホストの設定が ホームディレクトリー以外の書き込みを禁止している場合、有効なオプションです。

レンタルサーバーなどで幅広く使ってもらうことを目的とするなら `cake` の方がよさそう

**Comment by ryuring** [comment]
@seto1 cake に変更しました。

なお、設定値変更の仕様として、app.php の変更は、app_local.php とし、
plugins/baser-core/config/setting.php の変更は、config/setting.php でできるようにしました。
