### ISSUE TITLE
エイリアスの削除ができない

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#613]
コンテンツ管理にも編集画面にも削除ボタンがない

<img width="335" alt="スクリーンショット 2022-06-09 10 34 40" src="https://user-images.githubusercontent.com/30764014/172745522-3e602ab7-f396-4a0d-8045-a4b484ae15fb.png">

<img width="871" alt="スクリーンショット 2022-06-09 10 34 50" src="https://user-images.githubusercontent.com/30764014/172745531-d377f562-108c-4b02-8405-7c3d8e566cf1.png">

**Comment by seto1** [comment]
エイリアス追加直後は削除リンクが表示されるし削除も実行できる

<img width="640" alt="スクリーンショット 2022-06-09 14 50 32" src="https://user-images.githubusercontent.com/30764014/172773952-a050bb30-12ba-40fc-b323-6c70001f1449.png">

再度画面を開くと不可

<img width="769" alt="スクリーンショット 2022-06-09 14 50 49" src="https://user-images.githubusercontent.com/30764014/172773967-854a6974-3059-46ce-8dd8-9844e7096455.png">

**Comment by seto1** [comment]
- BcContentsEventListener->formAfterSubmit に削除ボタンを表示するかの条件が記載されているので要調整
- 削除可能かどうかに条件があるのであれば、 ContentsService->delete あたりでもチェックしないと脆弱性になりそう

**Comment by seto1** [comment]
- ルートフォルダのエイリアスを作成した際の `site_root` 判定で削除できない
	- 4系だとエイリアスの `site_root` は空
- 削除判定の置き場
	- コントローラーもしくはサービス　API側も必要
	- Permissionの判定の仕様との兼ね合い

**Comment by ryuring** [comment]
@seto1 現在正常に動作しているようですので一旦クローズします。解決してないようでしたら戻してください。
