### ISSUE TITLE
plugins/baser-core/config/session.php が読み込まれていない

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#619]
https://github.com/baserproject/ucmitz/blob/dev/plugins/baser-core/config/session.php

セッションファイルの設定方法が変更になったので不要になったのかも
https://github.com/baserproject/ucmitz/commit/ae7590ad982421c7bbd73c7e7f6c261bb67128ef
必要な設定が引き継がれているか要確認

**Comment by ryuring** [comment]
@seto1 ですね、session.php はまだ未精査です。
baser-coreが提供する設定は、session.php で設定し、カスタマイズは、app/config/ 内でできるようにしたいです。
