### ISSUE TITLE
管理画面用のAPIとフロント用のAPIについて

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#621]
- 現在のAPIはどれもログイン前提としているように見える
- フロント用のAPIは存在するか調査
- もし新しく対応するのであれば現在のApiはApi/Admin配下に移動したほうがいいかも

**Comment by ryuring** [comment]
@seto1 そうなんよ、懸案中のまま止まってました

**Comment by ryuring** [comment]
こちら完了のためクローズします。
