### ISSUE TITLE
プラグインインストール時にシンボリックリンク作成

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#639]
https://book.cakephp.org/4/ja/console-commands/plugin.html#id3

プラグインフォルダの中のwebroot配下のファイルに、PHPを介さずアクセスできるようになるのでパフォーマンスの改善になる

**Comment by seto1** [comment]
git管理や他サーバーに反映する際に問題が起きそうな気がするのでクローズします。

**Comment by ryuring** [comment]
@seto1 こちらは、現在、docker/init.sh で自動作成しています。
また、今後の開発では、ローカルでは無視設定にし、本番環境においてはインストール時に自動作成するか、管理画面に作成するボタンを作る方向でいきたいと考えています。

一旦、戻します。

**Comment by ryuring** [comment]
こちらは自動生成する形で実装完了です。
