### ISSUE TITLE
ajaxのエラーメッセージに不要な情報が含まれている

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#649]
<img width="862" alt="スクリーンショット 2022-06-29 17 52 52" src="https://user-images.githubusercontent.com/30764014/176395408-7a8f092e-0991-41e9-9a0c-4f3b918d58aa.png">

<img width="954" alt="スクリーンショット 2022-06-29 17 53 41" src="https://user-images.githubusercontent.com/30764014/176395425-494f3b85-1c7b-4ed6-a9b9-470d43706b11.png">

**Comment by ryuring** [comment]
API側の返却のインターフェイスが変わったのに、受け取り側は調整していないという感じでしょうね。 @seto1 

コンテンツ管理まわりこういいうのがかなり多いのでメンション入れておきますw
@humuhimi
