### ISSUE TITLE
コンテンツ管理 コンテンツ削除時にコンテンツタイトルがエスケープされずに表示される

### ISSUE THREAD

**Issue by seto1** [baserproject/ucmitz#650]
<img width="983" alt="スクリーンショット 2022-06-30 12 07 01" src="https://user-images.githubusercontent.com/30764014/176584336-619244a4-6915-4f2f-a993-155a93465051.png">

他のメッセージ表示箇所も確認が必要

**Comment by ryuring** [comment]
なおっているようなのでクローズ
