### ISSUE TITLE
BcBaserHelper::set()のユニットテスト

### ISSUE THREAD

**Issue by hiraokakoichi** [baserproject/ucmitz#655]

**Comment by ryuring** [comment]
@hiraokakoichi set() は、View->set() のラッパーなのでテスト不要です。マーキングだけお願いします。

**Comment by ryuring** [comment]
> View->set() のラッパーなのでテスト不要です。

View->set() 側でテストが書かれているのでテスト済とみなすといった感じです。

**Comment by hiraokakoichi** [comment]
承知しました！ご指摘ありがとうございます。
