### ISSUE TITLE
BcBaserHelper.getKeywords()のユニットテスト

### ISSUE THREAD

**Issue by hiraokakoichi** [baserproject/ucmitz#657]

**Comment by hiraokakoichi** [comment]
$this->_View->getRequest()->getParam('Site.keyword')で取得する値の変更方法がわかるまで保留。

**Comment by hiraokakoichi** [comment]
サイトキーワードの仕様（構造）に大きな変更があり、ユニットテストを新仕様に対応させるには時間がかかるため一旦スルー。

**Comment by ryuring** [comment]
メディアブリッジさんに任せる前提で、一旦、クローズします
