### ISSUE TITLE
BcBaserHelper.getTitle()のユニットテスト

### ISSUE THREAD

**Issue by hiraokakoichi** [baserproject/ucmitz#661]

**Comment by hiraokakoichi** [comment]
テスト実行時にエラー発生

エラー箇所：$this->_getRequest('/about');
エラーメッセージ：Error: Call to undefined method BaserCore\Test\TestCase\View\Helper\BcBaserHelperTest::_getRequest()

**Comment by ryuring** [comment]
こちらもメソッド名変更です。よろしくお願いします。

**Comment by ryuring** [comment]
メディアブリッジさんに任せる前提で、一旦、クローズします
