### ISSUE TITLE
BcBaserHelper.title()のユニットテスト

### ISSUE THREAD

**Issue by hiraokakoichi** [baserproject/ucmitz#662]

**Comment by hiraokakoichi** [comment]
エラー発生

エラー箇所：$this->_getRequest('/about');
エラーメッセージ：Error: Call to undefined method BaserCore\Test\TestCase\View\Helper\BcBaserHelperTest::_getRequest()

**Comment by ryuring** [comment]
@hiraokakoichi `$this->_getRequest()` が、 ucmitz にて、 `$this->getRequest()` に変更になりましたので、調整お願いします。

**Comment by hiraokakoichi** [comment]
@ryuring 
> $this->_getRequest() が、 ucmitz にて、 $this->getRequest() に変更になりましたので、調整お願いします。
改めてユニットテストを行いましたが、失敗しました。原因は、BcBaser::setTitleが未完成であるためでした。なお、BcBaser::setTitleのユニットでは以下のエラーメッセージが表示されます。
```
1) BaserCore\Test\TestCase\View\Helper\BcBaserHelperTest::testSetTitle
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'会社案内｜baserCMS inc. [デモ]'
+'baserCMS inc.'
```

[プルリクURL](https://github.com/baserproject/ucmitz/pull/686)

**Comment by ryuring** [comment]
メディアブリッジさんに任せる前提で、一旦、クローズします
