### ISSUE TITLE
BcBaserHelper.header()のユニットテスト

### ISSUE THREAD

**Issue by hiraokakoichi** [baserproject/ucmitz#664]
baser4系のテストコードには期待されるheaderの出力が正規表現で書かれているが、そのパターンとbaser5系で実際に出力されるheaderがマッチしないためにテスト実行時にエラーがでる。
単に正規表現をbaser5のheaderを元に書き直せばいいだけなのかもしれない。

エラー箇所：`$this->expectOutputRegex('/<div id="Header">.*<a href="\/sitemap">サイトマップ<\/a>.*<\/li>.*<\/ul>.*<\/div>.*<\/div>/s');`

実際に出力される文字列：`<header class="bs-header">
        <div class="bs-header__inner">
            <a href="/"><img src="bc_front/img/logo.png" class="bs-header__logo" alt=""/></a>
        </div>

        <div class="bs-header__menu-button" id="BsMenuBtn">
            <span></span>
            <span></span>
            <span></span>
        </div>

        <nav class="bs-header__nav" id="BsMenuContent">
                
            <ul class="ul-level-1 bs-global-menu">
                <li class="bs-global-menu-item li-level-1 current">
                    <a href="/" class="bs-global-menu-item--link">トップページ</a>
                </li>
                <li class="bs-global-menu-item li-level-1">
                    <a href="/news/" class="bs-global-menu-item--link">NEWS(※関連Fixture未完了)</a>
                </li>
                <li class="bs-global-menu-item li-level-1">
                    <a href="/about" class="bs-global-menu-item--link">会社案内</a>
                </li>
                <li class="bs-global-menu-item li-level-1">
                    <a href="/service/" class="bs-global-menu-item--link">サービス</a>
                    <div class="bs-global-menu-sub">
                        <ul class="menu ul-level-2">
                            <li class="menu-content li-level-2">
                                <a href="/service/service1">サービス１</a>
                            </li>
                            <li class="menu-content li-level-2">
                                <a href="/service/service2">サービス２</a>
                            </li>
                            <li class="menu-content li-level-2">
                                <a href="/service/service3">サービス３</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="bs-global-menu-item li-level-1">
                    <a href="/contact/" class="bs-global-menu-item--link">お問い合わせ(※関連Fixture未完了)</a>
                </li>
                <li class="bs-global-menu-item li-level-1">
                    <a href="/tree_deleted/" class="bs-global-menu-item--link">ツリー階層削除用フォルダー(親)</a>
                    <div class="bs-global-menu-sub">
                        <ul class="menu ul-level-2">
                            <li class="menu-content li-level-2">
                                <a href="/tree_deleted/tree_child/">ツリー階層削除用フォルダー(子)</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="bs-global-menu-item li-level-1">
                    <a href="/test_edit/" class="bs-global-menu-item--link">testEdit</a>
                    <div class="bs-global-menu-sub">
                        <ul class="menu ul-level-2">
                            <li class="menu-content li-level-2">
                                <a href="/test_edit/">testEditのエイリアス</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="bs-global-menu-item li-level-1">
                    <a href="/en/サイトID3の固定ページ" class="bs-global-menu-item--link">サイトID3の固定ページ</a>
                </li>
                <li class="bs-global-menu-item li-level-1">
                    <a href="/en/サイトID3の固定ページ2" class="bs-global-menu-item--link">サイトID3の固定ページ2</a>
                </li>
                <li class="bs-global-menu-item li-level-1">
                    <a href="/en/サイトID3の固定ページ3" class="bs-global-menu-item--link">サイトID3の固定ページ3</a>
                </li>
            </ul>
        </nav>

</header>`

**Comment by ryuring** [comment]
@hiraokakoichi フロントエンド側がまだ完成してないのでスキップした方がよさそうですね。

**Comment by ryuring** [comment]
メディアブリッジさんに任せる前提で、一旦、クローズします
