### ISSUE TITLE
BcBaserHelper.pagination()のユニットテスト

### ISSUE THREAD

**Issue by hiraokakoichi** [baserproject/ucmitz#665]
baser4系では成功していたテストコードでこけている。原因を探るため以下の操作を行い、結果を確認した。

[操作１]baser4系のテストコードをそのまま実行
[結果１]`$this->BcBaser->request->params['paging']['Model']`は存在しないとのエラーが発生
↓
[操作２]そもそも`$this->BcBaser->request`がnullだったので`$this->BcBaser->request = $this->getRequest('/');`でリクエストを作成
[結果２]paramはprotectedだからアクセスできないとのエラーが発生
↓
[操作３]`$this->BcBaser->request->params['paging']['Model']`への代入処理をコメントアウトし、リクエストを作成した直後に`$this->BcBaser->pagination();`を実行
[結果３]paginations/default.phpが見つからないとのエラーが発生

**Comment by ryuring** [comment]
@hiraokakoichi ページネーションは仕様が変わっているので一旦、スキップした方が良さそうですね

**Comment by ryuring** [comment]
メディアブリッジさんに任せる前提で、一旦、クローズします
