### ISSUE TITLE
BcBaserHelper.content()のユニットテスト

### ISSUE THREAD

**Issue by hiraokakoichi** [baserproject/ucmitz#666]
baser４系では問題がなかったテストコードでエラーが発生している。

原因：テストコード中にBcAppViewクラスが使われているが、そのクラスはまだbaser5で実装されていない。

BcAppView.phpのはじめの３行を抜粋

```
<?php
// TODO : コード確認要
return;
```

**Comment by ryuring** [comment]
メディアブリッジさんに任せる前提で、一旦、クローズします
