### ISSUE TITLE
BcBaserHelper.icon()のユニットテスト

### ISSUE THREAD

**Issue by hiraokakoichi** [baserproject/ucmitz#680]

**Comment by hiraokakoichi** [comment]
testIconメソッドを実行した際のエラー文は以下の通り

> 1) BaserCore\Test\TestCase\View\Helper\BcBaserHelperTest::testIcon
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'<link href="/favicon.ico" type="image/x-icon" rel="icon"/><link href="/favicon.ico" type="image/x-icon" rel="shortcut icon"/>\n
> +'<link href="favicon.ico" type="image/x-icon" rel="icon"/><link href="favicon.ico" type="image/x-icon" rel="shortcut icon"/>\n
>  '

**Comment by ryuring** [comment]
メディアブリッジさんに任せる前提で、一旦、クローズします
