### ISSUE TITLE
APIのURL構成を検討

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#727]
APIについて、現状は、JWT認証を前提としている。
APIでの処理については、パブリック（公開されたデータ）なものとクローズドなもの（非公開のデータ、登録、更新、削除）があるため、URLの階層を分けるか検討する。

現在は、名前空間 `BaserCore\Controller\Api` にて、`BcApiController ` を継承する事により自動的に認証がかかるようになっている。

URLは次の形式となる。

```
https://localhost/baser/api/baser-core/user_groups/index.json
https://localhost/baser/api/baser-core/user_groups.json （REST API）
```

これを次のように分けるかどうかを検討する。

```
// パブリックな処理
https://localhost/baser/api/baser-core/user_groups/index.json
// クローズドな処理
https://localhost/baser/api/admin/baser-core/user_groups/index.json
```

ただし、baserCMSでは、admin は、認証されている事を指すのではなく、管理画面を指している。
また、URLを分ける事で複雑になってしまう側面もあるため、URL体系は同一として次のように、一つ一つパブリックな処理を許可する前提とする事も検討する。

```php
$this->Authentication->allowUnauthenticated(['index']);
```

また、セキュリティの観点から、パブリックな処理をそもそも許容するのかどうかも検討する。
（ユーザー認証ではなく、OAuthやbasic認証などのアプリーケーション認可）

**Comment by seto1** [comment]
> また、URLを分ける事で複雑になってしまう側面もあるため、URL体系は同一として次のように、一つ一つパブリックな処理を許可する前提とする事も検討する。

同じURLなのにパブリックとプライベートで結果が異なるケースはありますね。

例: ブログ記事一覧の取得
パブリックは公開記事のみ
プライベートは非公開されている記事も取得可

同じ関数の中で、認証されているかどうかで処理を分けるという手もあるかもしれませんが、それはそれで複雑になりますね。

> また、セキュリティの観点から、パブリックな処理をそもそも許容するのかどうかも検討する。

てっきり、SPAやアプリなどからのアクセスを前提とした、セキュリティ上アクセスされても問題ない処理だけを置くものと思ってました。

**Comment by ryuring** [comment]
@seto1 

> セキュリティ上アクセスされても問題ない処理

これを誰かきめるのかっていう問題があるんですよね。

サイトの仕様によってアクセスされていいデータが変わるので。

**Comment by ryuring** [comment]
今度のネクストで話し合えたらと思います😊

**Comment by ryuring** [comment]
こちらの件、下記資料にまとめたのでクローズします。
https://baserproject.github.io/5/ucmitz/specification/baser-core/common/permission.html
