### ISSUE TITLE
【Web API】実装方法について検討

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#73]
CakePHPでは、RequestHandlerコンポーネントを利用することで簡単にJSON用のビューに切り替えることができるようです。
例えば次の改修の例では、`/baser/plugins/index` に拡張子 `.json` をつけるだけでプラグイン一覧のJSONが取得できます。
https://github.com/ryuring/ucmitz/commit/7528a0cb4b58d3079984603fa574f47838580747

これは、RequestHandlerコンポーネントが拡張子を判断し、Viewクラスを `JsonView` に自動で切り替る仕様となっているためです。

`$this->viewBuilder()->setOption('serialize', ['plugins']);` で、JSON化の対象を指定する形になります。

また、リソースに対してのアクセスとしてのREST対応もルーティング設定で簡単にHTTPメソッドとコントローラーアクションを紐付けできそうです。
https://book.cakephp.org/3/ja/development/routing.html#resource-routes

検討材料としては次のとおり。

- できればレンダリング用のアクションとAPI用のアクションをまとめて似たような処理をなくしたい
    - まとめる場合、APIで呼び出した場合、レンダリング用の処理を行わないようにしたい
    - まとめる場合、レンダリング用の処理はコントローラーで書かず、全てビュー側のヘルパーで解決させる？
- 現在、管理画面用のコントローラーとフロントのコントローラーを分ける前提の設計となっている
    - 管理画面用コントローラーではではCRUD同樣、リソースへのアクセスとしてREST化する？
    - フロント用コントローラーでは表示用として、公開状態を加味した読み取り専用のアクセスだけを提供する？

**Comment by gondoh** [comment]
@ryuring 
RequestHandlerを利用したJSONの出力は機能として問題ないと思いますが、管理上の問題は出そうかと思っています。
例えばユーザ一覧はJSON出力機能があるのに、ユーザ詳細は無い、というような状況が発生するかと思います。
Rails1系、Cake2系から拡張子判別によるレスポンスの切り替えはあったと思いますがうまく実装管理できずばらばらなのはみたことがあるためです。

そのためデータ取得の処理はモデルに実装しアクションも個別に分けたほうがいいのかなとは思いますがどうでしょうか。

ご確認ください！

**Comment by ryuring** [comment]
@gondoh 今、Slackの方で少しやり取りしてますね。サービスレイヤーを作るとか作らないとか。

**Comment by ryuring** [comment]
DIコンテナを利用しサービスクラスを利用する方針となりました。
既に実装済みです。クローズします。
