### ISSUE TITLE
Api\SearchIndexesController::index() の作成

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#829]
https://docs.google.com/spreadsheets/d/1YT5PuZQdDNU0wrZdqYbh74KuLSw1SIt4_EKwPWOfDKA/edit#gid=0&range=G189

**Comment by HungDV2022** [comment]
@ryuring 
https://github.com/baserproject/ucmitz/pull/848
すみません、
こちらのタスクは対応しましたがPRのタイトルが間違っているからお手数ですがCloseをお願いします「
