### ISSUE TITLE
BcCacheBehavior 実装

### ISSUE THREAD

**Issue by momofff** [baserproject/ucmitz#858]

**Comment by ryuring** [comment]
こちらは実装しないかもしれません。
一旦保留でお願いします。
@momofff

**Comment by momofff** [comment]
@ryuring 
コメントありがとうございます！かしこまりました！
#732 を対応するにあたり下記の処理を実装したく BcCacheBehavior を実装しようと思ったのですが、一旦別の方法で実装する形でよろしいでしょうか？
https://github.com/baserproject/ucmitz/blob/9f922d8fa776495ff8140ab00391027fae5c7294/plugins/baser-core/src/Service/ContentsService.php#L551-L568

**Comment by momofff** [comment]
@ryuring 
かしこまりました！ありがとうございます！

**Comment by ryuring** [comment]
BcCacheBehaviorは使わない方向でいきます
