### ISSUE TITLE
BcDatabaseService::writeCsv() のユニットテスト（dev-#8）

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#897]
- [x] テーブルを指定していCSVファイルの書き出しを確認
- [ ] encoding オプションを SJIS にし、書き出しファイルのエンコードを確認
- [x] init オプションを指定して、id, modified, created が空になっていることを確認

**Comment by ryuring** [comment]
こちら、これから作成する BcDatabaseService に移動します。
一旦、保留でお願いします。

**Comment by HungDV2022** [comment]
@ryuring 
こちらのタスクはBcDatabaseServiceに移動したようですからユニットテストを対応できますか

**Comment by ryuring** [comment]
@HungDV2022 はい、お願いします
