### ISSUE TITLE
ThemesService::load_default_data_pattern() のユニットテスト（dev-#8）

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#925]
- [ ] ステータスを確認
- [ ] メッセージを確認
- [ ] リダイレクトを確認

**Comment by zebeel** [comment]
@ryuring ThemesService::load_default_data_pattern()が存在しません。

**Comment by ryuring** [comment]
loadDefaultDataPattern として実装済なことを確認しました。クローズします。
