### ISSUE TITLE
ThemesController::add() のユニットテスト（dev-#8）

### ISSUE THREAD

**Issue by ryuring** [baserproject/ucmitz#926]
- [x] ステータスの確認
- [x] メッセージの確認
- [x] リダイレクトの確認

**Comment by zebeel** [comment]
@ryuring 
Admin/ThmesControllerTestにテスト追加しましたがエラーが発生しています。ソースは以下の通りです。


    public function test_add()
    {
        $this->enableSecurityToken();
        $this->enableCsrfToken();

        $path = ROOT . DS . 'plugins' . DS . 'BcSpaSample';
        $zipSrcPath = TMP  . 'zip' . DS;
        $folder = new Folder();
        $folder->create($zipSrcPath, 0777);
        $theme = 'BcSpaSample2';
        $folder->copy($zipSrcPath . $theme, ['from' => $path, 'mode' => 0777]);
        $zip = new ZipArchiver();
        $testFile = $zipSrcPath . $theme . '.zip';
        $zip->archive($zipSrcPath, $testFile, true);

        $this->setUploadFileToRequest('file', $testFile);
        $this->post('/baser/admin/baser-core/themes/add');

        $this->assertResponseCode(302);
        $this->assertRedirect([
            'plugin' => 'BaserCore',
            'prefix' => 'Admin',
            'controller' => 'themes',
            'action' => 'index'
        ]);
        $this->assertFlashMessage("テーマファイル「' . $theme . '.zip」を追加しました。");

        $folder = new Folder();
        $folder->delete(ROOT . DS . 'plugins' . DS . $theme);
        $folder->delete($zipSrcPath);
    }

テスト結果は以下の通りです。

1) BaserCore\Test\TestCase\Controller\Admin\ThemesControllerTest::test_add
Failed asserting that `302` matches response status code `400`.


やり方はAdmin/ThmesControllerTest::testAdd()から参加しましたが動けないです。
お手数ですがこちらのソースを見てもらえないでしょうか？
